import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Footer } from '../components/Footer';
import { Links } from '../components/Links';
import { Headline } from '../components/Headline';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Headline
          page='about'
          number={1111}
          array={[1, 2, 3]}
          obj={{ foo: 'foo', bar: 'bar' }}
          boolean
        ></Headline>
        <Links> code={<code className={styles.code}>about.js</code>}</Links>
      </main>
      <Footer></Footer>
    </div>
  );
}
